<?php

if (!defined('BASEPATH')) {
    exit('No direct script access allowed');
}

class Product_orders_model extends CI_Model
{

    public $table = 'product_orders';
    public $id = 'id_product_order';
    public $order = 'DESC';

    public function __construct()
    {
        parent::__construct();
    }

    // datatables
    public function json()
    {
        $this->datatables->select('products.id_product, name_product, product_orders.id_product_order,type_order,direction,qty,before,after,date,id,detail_order');
        $this->datatables->from('product_orders');
        //add this line for join
        $this->datatables->join('products', 'product_orders.id_product = products.id_product');
        $this->datatables->add_column('action', anchor(site_url('admin/product_orders/read/$1'), 'Read'), 'id_product_order');
        return $this->datatables->generate();
    }

    // get all
    public function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    public function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    public function total_rows($q = null)
    {
        $this->db->like('id_product_order', $q);
        $this->db->or_like('id_product', $q);
        $this->db->or_like('type_order', $q);
        $this->db->or_like('qty', $q);
        $this->db->or_like('before', $q);
        $this->db->or_like('after', $q);
        $this->db->or_like('date', $q);
        $this->db->or_like('id', $q);
        $this->db->or_like('detail_order', $q);
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    public function get_limit_data($limit, $start = 0, $q = null)
    {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_product_order', $q);
        $this->db->or_like('id_product', $q);
        $this->db->or_like('type_order', $q);
        $this->db->or_like('qty', $q);
        $this->db->or_like('before', $q);
        $this->db->or_like('after', $q);
        $this->db->or_like('date', $q);
        $this->db->or_like('id', $q);
        $this->db->or_like('detail_order', $q);
        $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    public function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    public function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    public function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Product_orders_model.php */
/* Location: ./application/models/Product_orders_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2025-01-13 04:45:38 */
/* http://harviacode.com */