<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class T_buletin_model extends CI_Model
{

    public $table = 't_buletin';
    public $id = 'id_buletin';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id_buletin,judul_b,id_user,artikel,cover_gambar,date,time,id_kate');
        $this->datatables->from('t_buletin');
        //add this line for join
        //$this->datatables->join('table2', 't_buletin.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('admin/t_buletin/read/$1'),'Read')." | ".anchor(site_url('admin/t_buletin/update/$1'),'Update')." | ".anchor(site_url('admin/t_buletin/delete/$1'),'Delete','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id_buletin');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    function get_all_list($limit, $start){
        $query = $this->db->get($this->table, $limit, $start);
        return $query->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_buletin', $q);
	$this->db->or_like('judul_b', $q);
	$this->db->or_like('id_user', $q);
	$this->db->or_like('artikel', $q);
	$this->db->or_like('cover_gambar', $q);
	$this->db->or_like('date', $q);
	$this->db->or_like('time', $q);
	$this->db->or_like('id_kate', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_buletin', $q);
	$this->db->or_like('judul_b', $q);
	$this->db->or_like('id_user', $q);
	$this->db->or_like('artikel', $q);
	$this->db->or_like('cover_gambar', $q);
	$this->db->or_like('date', $q);
	$this->db->or_like('time', $q);
	$this->db->or_like('id_kate', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file T_buletin_model.php */
/* Location: ./application/models/T_buletin_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-11-16 17:08:46 */
/* http://harviacode.com */