<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class T_donasi_model extends CI_Model
{

    public $table = 't_donasi';
    public $id = 'id_donasi';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_donasi', $q);
	$this->db->or_like('id_user', $q);
	$this->db->or_like('donatur', $q);
	$this->db->or_like('telepon', $q);
	$this->db->or_like('alamat', $q);
	$this->db->or_like('uang', $q);
	$this->db->or_like('barang', $q);
	$this->db->or_like('ket', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->select('t_donasi.id_donasi,id_user,donatur,telepon,t_donasi.alamat,uang,barang,ket,users.id,users.username');
        $this->db->from($this->table);
        $this->db->join('users', 't_donasi.id_user = users.id');
        $this->db->order_by('t_donasi.id_donasi', $this->order);
        $this->db->like('t_donasi.id_donasi', $q);
    	$this->db->or_like('t_donasi.id_user', $q);
    	$this->db->or_like('t_donasi.donatur', $q);
    	$this->db->or_like('t_donasi.telepon', $q);
    	$this->db->or_like('t_donasi.alamat', $q);
    	$this->db->or_like('t_donasi.uang', $q);
    	$this->db->or_like('t_donasi.barang', $q);
    	$this->db->or_like('t_donasi.ket', $q);
    	$this->db->limit($limit, $start);
        return $this->db->get()->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file T_donasi_model.php */
/* Location: ./application/models/T_donasi_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-12-02 01:19:08 */
/* http://harviacode.com */