<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class T_jadwal_model extends CI_Model
{

    public $table = 't_jadwal';
    public $id = 'id_jadwal';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id_jadwal,tgl,jam,nama_kegiatan,deskripsi');
        $this->datatables->from('t_jadwal');
        //add this line for join
        //$this->datatables->join('table2', 't_jadwal.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('admin/t_jadwal/read/$1'),'Read')." | ".anchor(site_url('admin/t_jadwal/update/$1'),'Update')." | ".anchor(site_url('admin/t_jadwal/delete/$1'),'Delete','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id_jadwal');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_jadwal', $q);
	$this->db->or_like('tgl', $q);
	$this->db->or_like('jam', $q);
	$this->db->or_like('nama_kegiatan', $q);
	$this->db->or_like('deskripsi', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_jadwal', $q);
	$this->db->or_like('tgl', $q);
	$this->db->or_like('jam', $q);
	$this->db->or_like('nama_kegiatan', $q);
	$this->db->or_like('deskripsi', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file T_jadwal_model.php */
/* Location: ./application/models/T_jadwal_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-11-13 02:53:32 */
/* http://harviacode.com */