<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class T_sholat_model extends CI_Model
{

    public $table = 't_sholat';
    public $id = 'id_sholat';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id_sholat,waktu_sholat,hari,imam,muadzin');
        $this->datatables->from('t_sholat');
        //add this line for join
        //$this->datatables->join('table2', 't_sholat.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('admin/t_sholat/read/$1'),'Read')." | ".anchor(site_url('admin/t_sholat/update/$1'),'Update')." | ".anchor(site_url('admin/t_sholat/delete/$1'),'Delete','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id_sholat');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_sholat', $q);
	$this->db->or_like('waktu_sholat', $q);
	$this->db->or_like('hari', $q);
	$this->db->or_like('imam', $q);
	$this->db->or_like('muadzin', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_sholat', $q);
	$this->db->or_like('waktu_sholat', $q);
	$this->db->or_like('hari', $q);
	$this->db->or_like('imam', $q);
	$this->db->or_like('muadzin', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file T_sholat_model.php */
/* Location: ./application/models/T_sholat_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-11-13 02:59:41 */
/* http://harviacode.com */