<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class T_kategori extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('T_kategori_model');
        $this->load->library('form_validation');        
	$this->load->library('datatables');
    }

    public function index()
    {
        $data = array('title' => 't_kategori');
        $this->template->load('template','admin/t_kategori/t_kategori_list', $data);
    } 
    
    public function json() {
        header('Content-Type: application/json');
        echo $this->T_kategori_model->json();
    }

    public function read($id) 
    {
        $row = $this->T_kategori_model->get_by_id($id);
        if ($row) {
            $data = array(
                'title' => 'Read',
		'id_kate' => $row->id_kate,
		'nama_kate' => $row->nama_kate,
		'status' => $row->status,
	    );
            $this->template->load('template','admin/t_kategori/t_kategori_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('admin/t_kategori'));
        }
    }

    public function create() 
    {
        $data = array(
            'title' => 'Create',
            'button' => 'Create',
            'action' => site_url('admin/t_kategori/create_action'),
	    'id_kate' => set_value('id_kate'),
	    'nama_kate' => set_value('nama_kate'),
	    'status' => set_value('status'),
	);
        $this->template->load('template','admin/t_kategori/t_kategori_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'nama_kate' => $this->input->post('nama_kate',TRUE),
		'status' => $this->input->post('status',TRUE),
	    );

            $this->T_kategori_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('admin/t_kategori'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->T_kategori_model->get_by_id($id);

        if ($row) {
            $data = array(
                'title' => 'Update',
                'button' => 'Update',
                'action' => site_url('admin/t_kategori/update_action'),
		'id_kate' => set_value('id_kate', $row->id_kate),
		'nama_kate' => set_value('nama_kate', $row->nama_kate),
		'status' => set_value('status', $row->status),
	    );
            $this->template->load('template','admin/t_kategori/t_kategori_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('admin/t_kategori'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id_kate', TRUE));
        } else {
            $data = array(
		'nama_kate' => $this->input->post('nama_kate',TRUE),
		'status' => $this->input->post('status',TRUE),
	    );

            $this->T_kategori_model->update($this->input->post('id_kate', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('admin/t_kategori'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->T_kategori_model->get_by_id($id);

        if ($row) {
            $this->T_kategori_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('admin/t_kategori'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('admin/t_kategori'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('nama_kate', 'nama kate', 'trim|required');
	$this->form_validation->set_rules('status', 'status', 'trim|required');

	$this->form_validation->set_rules('id_kate', 'id_kate', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file T_kategori.php */
/* Location: ./application/controllers/T_kategori.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-11-16 17:08:54 */
/* http://harviacode.com */